print("Hola")
nombre = input("¿Me puedes indicar tu nombre?: ")
print('Gracias! ' + nombre.capitalize() + ' Ahora necesito tu apellido: ')
apellido = input()
print("Perfecto! Bienvenido", nombre.capitalize(), apellido.capitalize() + " al maravilloso mundo de Python")
