print("ola, te voy acer unas preguntas para conocerte mejor")
nombre= input ("Introduce tu nombre \n")
edad= input ("Introduce tu edad \n")
ciudad= input("Dime de que ciudad vives \n")
print ("ola " + nombre + ". Tu tienes " + edad + " años y vives en " + ciudad)